version: '3.8'

services:
  web:
    build: .
    platform: linux/amd64
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CORS_ORIGINS=["*"]
      - PYTHONUNBUFFERED=1
    command: python3 -m uvicorn main:app --host 0.0.0.0 --port 8000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    platform: linux/amd64
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PYTHONUNBUFFERED=1
    command: celery -A app.core.celery_app worker --loglevel=info --concurrency=4 --max-tasks-per-child=100
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    shm_size: 2g
    tmpfs:
      - /tmp:exec,mode=1777
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
