version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CORS_ORIGINS=["*"]
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - app-network

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - web
    volumes:
      - .:/app
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  flower:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A app.core.celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - celery_worker
    networks:
      - app-network

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge 